### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kalihackerCD43** [metachar/Mercury#15]
root@kali:~/Mercury# ./Mercury.py 
/usr/bin/env: ‘python\r’: No such file or directory

i use kali linux, how to fix?

**Comment by micahjmartin** [comment]
If you copied this script from windows, you will need to convert the line endings to unix. Here is a great [article](https://blog.codinghorror.com/the-great-newline-schism/) on the topic.

You can convert this using a tool called `dos2unix`

```
apt install dos2unix
```

Here is an answer on how to convert an entire directories newlines
https://stackoverflow.com/questions/11929461/how-can-i-run-dos2unix-on-an-entire-directory

**Comment by kalihackerCD43** [comment]
now i got this `root@kali:~/Mercury# ./Mercury.py 
Traceback (most recent call last):
  File "./Mercury.py", line 33, in <module>
    from pygoogling.googling import GoogleSearch
  File "/usr/local/lib/python2.7/dist-packages/pygoogling/googling.py", line 2, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
`

**Comment by kalihackerCD43** [comment]
i know what to do ` pip install --upgrade beautifulsoup4 && pip install --upgrade html5lib` this is the solution. thanks

**Comment by kalihackerCD43** [comment]
`pip install --upgrade beautifulsoup4 && pip install --upgrade html5lib`
