### ISSUE TITLE
Issue on Linux

### ISSUE THREAD

**Issue by dsgntech** [MetaChar/Mercury#2]
When getting to the terms page being called from Extras/Mercury, it's formatted for Windows so \Extras\Mercury.txt. Fixed the two references to that file with Linux formatted file paths, not sure if maybe there should be something after the OS check, if windows call this file, if linux call this one? Only other thing I've noticed on Linux is it doesn't seem to be picking up your coloration for the header and menus.

**Comment by MetaChar** [comment]
what are you running linux wise

**Comment by MetaChar** [comment]
"maybe there should be something after the OS check," That`s actually a really good idea and i will work on that soon!

**Comment by dsgntech** [comment]
I’m running a fully updated version of Kali. Sorry, from the install instructions I assumed till I got to the version check that it was designed for Windows. I can submit a copy of the script with all file references reformatted if that’ll save you some time. I’m also trying to get the browser.get function working on Linux using Firefox. I was thinking of a way to have that as a configuration option, so all places where chrome gets referenced would pull from an option set at start up maybe?

**Comment by MetaChar** [comment]
Sure a Firefox option seems great, but I don't know when I will be able to get to it and I fixed the code so linux users can open files in the code but I'm still working to make it linux 100% compatible

**Comment by dsgntech** [comment]
If you’d like I’ll give it a go and submit it. I don’t have a windows machine to test it’s compatibility. Definitely not the world’s best coder but I’ll give it a shot.
